/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectHotel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author mohmmal ali
 */
public class CleanRooms extends javax.swing.JFrame {
private static final String esername="root";
    private static final String Password="";
    private static final String dataConn="jdbc:mysql://localhost:3306/hotel_management";
    Connection sqlconn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    /**
     * Creates new form CleanRooms
     */
    public CleanRooms() {
        initComponents();
        upDateDB();
    }
public void upDateDB(){
        try
        {
           Class.forName("com.mysql.cj.jdbc.Driver");
                sqlconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management",
                        "root", "");
            pst = sqlconn.prepareStatement("select * from clean");
                    
            rs=pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable2.getModel();
                    RecordTable.setRowCount(0);
                    while(rs.next()){
                        Vector columnData = new Vector();
                        
                        for(i=1;i<=q;i++){
                            columnData.add(rs.getInt("Rooms_Rnumbuer"));
                            columnData.add(rs.getString("Rooms_hotel_hotel_id"));
                            columnData.add(rs.getString("employee_Employee_id"));

                        }
                        RecordTable.addRow(columnData);
                    }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel00 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextRnumbuer = new javax.swing.JTextField();
        jtextEmployee_id = new javax.swing.JTextField();
        jbtnAddR = new javax.swing.JButton();
        jbtnDeleteR = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnEXIT2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jtextHotel_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Rnumbuer");

        jLabel00.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel00.setText("     hotel managment system");
        jLabel00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Employee_id");

        jtextRnumbuer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextRnumbuerMouseClicked(evt);
            }
        });
        jtextRnumbuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextRnumbuerActionPerformed(evt);
            }
        });

        jbtnAddR.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbtnAddR.setText("Add Rooms");
        jbtnAddR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddRActionPerformed(evt);
            }
        });

        jbtnDeleteR.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbtnDeleteR.setText("Delete Rooms");
        jbtnDeleteR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteRActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnBack.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnEXIT2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbtnEXIT2.setText("EXIT");
        jbtnEXIT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEXIT2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rooms_Rnumbuer", "Rooms_hotel_hotel_id", "employee_Employee_id"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Hotel_id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel00, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtextEmployee_id, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(jtextRnumbuer)
                            .addComponent(jtextHotel_id, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnAddR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDeleteR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEXIT2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnAddR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbtnDeleteR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnEXIT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel00, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtextRnumbuer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtextEmployee_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextHotel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 860, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mohmmal ali\\Desktop\\Screenshot 2023-12-02 102218.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextRnumbuerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextRnumbuerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextRnumbuerMouseClicked

    private void jtextRnumbuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextRnumbuerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextRnumbuerActionPerformed

    private void jbtnAddRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddRActionPerformed
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management",
                "root", "");
            pst = sqlconn.prepareStatement("insert into clean(Rooms_Rnumbuer,Rooms_hotel_hotel_id,employee_Employee_id)value(?,?,?)");

            pst.setString(1, jtextRnumbuer.getText());
            pst.setString(2, jtextHotel_id.getText() );
            pst.setString(3, jtextEmployee_id.getText() );

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Room Added to clean");
            upDateDB();

        }
        catch(ClassNotFoundException ex){

            System.out.println(ex);
        }
        catch(SQLException ex){

            JOptionPane.showMessageDialog(this,ex);

        }
    }//GEN-LAST:event_jbtnAddRActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtextRnumbuer.setText("");
        jtextEmployee_id.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        Choose s1 = new Choose();
        s1.show();
        this.setVisible(false);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnEXIT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEXIT2ActionPerformed
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Hotel DataBase",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
    {
        System.exit(0);
        }
    }//GEN-LAST:event_jbtnEXIT2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable2.getModel();
        int SelectedRows = jTable2.getSelectedRow();

        jtextRnumbuer.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jbtnDeleteRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteRActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable2.getModel();
        int SelectRows = jTable2.getSelectedRow();

        try         {
            id = Integer.parseInt(RecordTable.getValueAt(SelectRows, 0).toString());
            int idd = Integer.parseInt(RecordTable.getValueAt(SelectRows, 1).toString());

            deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete item","Warning",JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management",
                    "root", "");
                pst = sqlconn.prepareStatement("delete from clean where Rooms_Rnumbuer =? AND Rooms_hotel_hotel_id=?");
                pst.setInt(1, id);
                pst.setInt(2, idd);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Room Deleted");
                upDateDB();
                jtextRnumbuer.setText("");
                jtextEmployee_id.setText("");

            }
        }
        catch(ClassNotFoundException ex){

            System.out.println(ex);
        }
        catch(SQLException ex){

            System.out.println(ex);
        }
    }//GEN-LAST:event_jbtnDeleteRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CleanRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CleanRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CleanRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CleanRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CleanRooms().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnAddR;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDeleteR;
    private javax.swing.JButton jbtnEXIT2;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtextEmployee_id;
    private javax.swing.JTextField jtextHotel_id;
    private javax.swing.JTextField jtextRnumbuer;
    // End of variables declaration//GEN-END:variables
}
